Fix mypy errors for unused comment and sshfs_threads needing type annotation
  $ make
  black -l 90 --check transient test scripts
  All done! ✨ 🍰 ✨
  17 files would be left unchanged.
  mypy --strict transient scripts
  transient/linux.py:11: error: unused 'type: ignore' comment
  transient/transient.py:371: error: Need type annotation for 'sshfs_threads' (hint: "sshfs_threads: List[<type>] = ...")
  Found 2 errors in 2 files (checked 16 source files)
  make: *** [Makefile:15: check-types] Error 1
  $ mypy --version
  mypy 0.790